"use client";

import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ShieldAlert, Check, AlertTriangle } from "lucide-react";

interface LegalDisclaimerModalProps {
  isOpen: boolean;
  onAccept: () => void;
}

export const LegalDisclaimerModal: React.FC<LegalDisclaimerModalProps> = ({
  isOpen,
  onAccept,
}) => {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
          {/* Backdrop Blur Overlay */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="fixed inset-0 bg-black/80 backdrop-blur-md"
            onClick={onAccept}
          />

          {/* Modal Container */}
          <motion.div
            initial={{ opacity: 0, scale: 0.92, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.92, y: 20 }}
            transition={{ type: "spring", stiffness: 350, damping: 26 }}
            className="relative w-full max-w-lg bg-[#0D151B] border border-emerald-500/30 rounded-2xl p-6 sm:p-8 shadow-[0_0_50px_rgba(16,185,129,0.2)] backdrop-blur-2xl text-zinc-100 z-10 overflow-hidden"
          >
            {/* Ambient Background Gradient Orbs */}
            <div className="absolute -top-24 -left-24 w-48 h-48 bg-emerald-500/15 rounded-full blur-3xl pointer-events-none" />
            <div className="absolute -bottom-24 -right-24 w-48 h-48 bg-teal-500/10 rounded-full blur-3xl pointer-events-none" />

            <div className="relative z-10 space-y-6">
              {/* Header */}
              <div className="flex items-start gap-4">
                <div className="w-13 h-13 sm:w-14 sm:h-14 rounded-2xl bg-white p-1.5 border border-emerald-500/30 shadow-[0_0_20px_rgba(16,185,129,0.25)] shrink-0 overflow-hidden flex items-center justify-center">
                  <img
                    src="/logo.jpeg"
                    alt="Project Access Logo"
                    className="w-full h-full object-contain rounded-xl select-none"
                  />
                </div>
                <div>
                  <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/10 border border-emerald-500/25 text-emerald-400 mb-1.5">
                    <ShieldAlert className="w-3.5 h-3.5" />
                    AI Assistant Legal Notice
                  </div>
                  <h2 className="text-xl font-bold text-white tracking-tight">
                    Disclaimer & User Guidance
                  </h2>
                </div>
              </div>

              {/* Notice Body */}
              <div className="space-y-3.5 text-sm text-zinc-300 leading-relaxed bg-[#121B22]/80 p-4 sm:p-5 rounded-xl border border-white/5">
                <p>
                  <strong className="text-white font-medium">Project Access</strong> operates strictly as an <span className="text-emerald-400 font-medium">AI-powered legal research assistant</span>. It provides statutory insights, case analysis, and document summaries for Indian Law.
                </p>

                <div className="flex gap-3 pt-2 text-emerald-200/90 text-xs sm:text-sm bg-emerald-500/10 p-3.5 rounded-lg border border-emerald-500/25">
                  <AlertTriangle className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <strong className="font-semibold text-emerald-300 block mb-0.5">
                      Consult a Qualified Lawyer
                    </strong>
                    The responses generated by this AI assistant do not constitute formal legal advice or create an attorney-client relationship. For final legal decisions, official filings, or court proceedings, always consult a licensed advocate or legal practitioner.
                  </div>
                </div>
              </div>

              {/* Action Button */}
              <div className="pt-1">
                <button
                  onClick={onAccept}
                  className="w-full py-3.5 px-6 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 font-bold text-sm transition-all duration-200 flex items-center justify-center gap-2 shadow-[0_0_25px_rgba(16,185,129,0.35)] hover:shadow-[0_0_30px_rgba(16,185,129,0.5)] active:scale-[0.99] cursor-pointer"
                >
                  <Check className="w-4 h-4 stroke-[3]" />
                  I Understand & Accept
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
